# Generated by Django 4.2.4 on 2023-10-14 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tougdo', '0002_remove_todoitem_todo_list_todoitem_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.SlugField(unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaggedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tougdo.tag')),
                ('todo_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tougdo.todoitem')),
            ],
            options={
                'ordering': ['todo_item'],
            },
        ),
        migrations.RemoveField(
            model_name='todomember',
            name='todo_item',
        ),
        migrations.RemoveField(
            model_name='todomember',
            name='todo_list',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
        migrations.DeleteModel(
            name='ToDoMember',
        ),
    ]
