# Generated by Django 4.2.4 on 2023-10-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougdo', '0004_rename_todoitem_item_alter_taggeditem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='done_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='is done'),
        ),
    ]
