# Generated by Django 4.2.4 on 2023-10-19 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tougdo', '0008_populate_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['due_date', 'priority']},
        ),
        migrations.AlterModelOptions(
            name='priority',
            options={'ordering': ['number']},
        ),
    ]
