# Generated by Django 4.2.4 on 2023-10-20 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougdo', '0009_alter_item_options_alter_priority_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
