# Generated by Django 4.2.4 on 2023-10-22 15:46

from django.db import migrations, models


def delete_null_tag_slugs(apps, schema_editor):
    Tag = apps.get_model("tougdo", "Tag")
    Tag.objects.filter(slug__isnull=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("tougdo", "0010_alter_item_due_date"),
    ]

    operations = [migrations.RunPython(delete_null_tag_slugs)]
